version: '3.8'

services:
  app:
    image: felippeks/m3s07-app:latest
    ports:
      - "8083:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/m3s07
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: m3s07
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"